services:
  - type: web
    name: hotel-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGO_URI
        value: mongodb://localhost:27017/hotelbooking
    autoDeploy: true
